import { join } from "node:path";

// iii 0.23 replaced the list-shaped config.yaml worker model with
// `iii compose`: an engine section plus registry containers. Registry
// package versions are the ones `iii project init` scaffolds for the
// 0.24 engine line.
export const COMPOSE_WORKER_VERSIONS = {
  state: "0.22.5-rc.1",
  http: "0.21.6",
  queue: "0.21.9",
  cron: "0.21.13-rc.1",
} as const;

export interface ComposeRenderOptions {
  dataDir: string;
  nodeBin: string;
  workerEntry: string;
  envFile: string;
  ports: {
    restPort: number;
    streamPort: number;
    viewerPort: number;
    enginePort: number;
  };
}

/** True for engine versions that require the compose worker model (>= 0.23). */
export function isComposeEngineVersion(version: string): boolean {
  const [major, minor] = version.split(".").map((part) => parseInt(part, 10));
  if (!Number.isFinite(major) || !Number.isFinite(minor)) return false;
  return major > 0 || minor >= 23;
}

function q(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/**
 * Renders the worker-compose.yaml that replaces the legacy list-shaped
 * iii-config.yaml for engine 0.23+. The engine owns the configuration,
 * worker-manager, http-functions, stream and sandbox workers; the project
 * declares state/http/queue/cron as registry containers and runs the
 * agentmemory worker through the app container's scripts.run.
 */
export function renderWorkerCompose(options: ComposeRenderOptions): string {
  const { ports } = options;
  const v = COMPOSE_WORKER_VERSIONS;
  return `# Generated by agentmemory. Edit via .env / CLI flags, not by hand.
namespace: default
startup_timeout: 360s

engine:
  url: ws://127.0.0.1:${ports.enginePort}
  workers:
    configuration:
      adapter:
        name: fs
        config:
          directory: ./config
    iii-worker-manager:
      host: 127.0.0.1
      port: ${ports.enginePort}
    iii-http-functions: {}
    iii-stream:
      host: 127.0.0.1
      port: ${ports.streamPort}
    iii-sandbox:
      auto_install: true

containers:
  state:
    worker: package://state
    version: "${v.state}"
    config_name: state
    working_dir: .
    config_override:
      adapter:
        name: kv
        config:
          store_method: file_based
          file_path: ${q(join(options.dataDir, "state_store.db"))}
  http:
    worker: package://http
    version: "${v.http}"
    config_name: http
    working_dir: .
    config_override:
      host: 127.0.0.1
      port: ${ports.restPort}
      default_timeout: 180000
      cors:
        allowed_origins: ["http://localhost:${ports.restPort}", "http://localhost:${ports.viewerPort}", "http://127.0.0.1:${ports.restPort}", "http://127.0.0.1:${ports.viewerPort}"]
        allowed_methods: [GET, POST, PUT, DELETE, OPTIONS]
  queue:
    worker: package://queue
    version: "${v.queue}"
    config_name: queue
    working_dir: .
  cron:
    worker: package://cron
    version: "${v.cron}"
    config_name: cron
    working_dir: .
  app:
    worker: path://.
    start_after: [state, http]
    working_dir: ${q(options.dataDir)}
    env_file: [${q(options.envFile)}]
    scripts:
      run: ${q(`${options.nodeBin} ${options.workerEntry}`)}
`;
}

/** Env handed to the app container; the engine URL/namespace come from the daemon. */
export function renderComposeEnv(options: {
  dataDir: string;
  runtimeDir: string;
  ports: { restPort: number; streamPort: number; viewerPort: number };
}): string {
  return [
    `AGENTMEMORY_DATA_DIR=${options.dataDir}`,
    `AGENTMEMORY_RUNTIME_DIR=${options.runtimeDir}`,
    `III_REST_PORT=${options.ports.restPort}`,
    `III_STREAM_PORT=${options.ports.streamPort}`,
    `III_VIEWER_PORT=${options.ports.viewerPort}`,
    "",
  ].join("\n");
}
